hydra:
  run:
    dir: ${output_path}
  sweep:
    dir: ${output_path}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - output_path
          - loadDir
          - dataset.sessions
defaults:
  - dataset: neural_speech_dataset.yaml
  - model: DeBCI.yaml

seed: 1234
distributed: false
with_clearml: true
batch_size: 8
max_epochs: 1
num_workers: 10
nproc_per_node: 2 # number of GPUs/CPUs
backend: 'gloo' # mpi, gloo, nccl https://pytorch.org/docs/stable/distributed.html#backends


output_path: chkpoint_contrastive


